name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust targets
      run: rustup +stable target add thumbv7em-none-eabihf
    - name: Install ARM GCC
      run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi
    - name: Build
      run: |
        cargo build --verbose --target=thumbv7em-none-eabihf --features=cortex-m-interrupt-critical-section
        cargo build --verbose --target=thumbv7em-none-eabihf --features=unsafe-no-critical-section,init-if-uninitialized,first-fit
