name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust targets
      run: rustup +stable target add thumbv7em-none-eabihf
    - name: Build
      run: |
        cargo build --verbose --target=thumbv7em-none-eabihf
        cargo build --verbose --target=thumbv7em-none-eabihf --features=sync,cortex-m
